// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3y9hmh5BG_-yStxK-mzQnpc2CdRc9NQs',
    appId: '1:634230901344:web:e906ec284b9a10814f9105',
    messagingSenderId: '634230901344',
    projectId: 'hewa-tell-air',
    authDomain: 'hewa-tell-air.firebaseapp.com',
    storageBucket: 'hewa-tell-air.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6XKAcTcAtyL3pnzHRo79J9dTFPGNk3_I',
    appId: '1:634230901344:android:1ea22a03b04081214f9105',
    messagingSenderId: '634230901344',
    projectId: 'hewa-tell-air',
    storageBucket: 'hewa-tell-air.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3HaW1qlgbBUngF-UD0FHbQzqshvUuTvA',
    appId: '1:634230901344:ios:11d45d1a05bf2a104f9105',
    messagingSenderId: '634230901344',
    projectId: 'hewa-tell-air',
    storageBucket: 'hewa-tell-air.appspot.com',
    iosClientId: '634230901344-2ufqju4298j81svi1k67jr1v6u41joa9.apps.googleusercontent.com',
    iosBundleId: 'com.testing.hewaTellAir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3HaW1qlgbBUngF-UD0FHbQzqshvUuTvA',
    appId: '1:634230901344:ios:08fc13136b7b9fc34f9105',
    messagingSenderId: '634230901344',
    projectId: 'hewa-tell-air',
    storageBucket: 'hewa-tell-air.appspot.com',
    iosClientId: '634230901344-dlaqoof1nnhban6grb2i7vrh801tjibi.apps.googleusercontent.com',
    iosBundleId: 'com.testing.hewaTellAir.RunnerTests',
  );
}
